var dataArray1 = [
  "Outside, 3, 6, 5",
  "1, ZAGIPH16PMLUXSNPBLA, Zagg iPhone Pro Max Lux Mag-Safe Black",
  "2, ZAGIPH16PMMILSNPIRI, Zagg iPhone Pro Max Mlian Iridescent",
  "3, ZAGIPH16PMSCSNPBLA, Zagg iPhone Pro Max Santa Cruz",
  "4, ZAGIPH16PMCPSNPCLR, Zagg CP Snap iPhone PM Case Clear",
  "5, ZAGIPH16PLUXSNPBLA, Zagg iPhone Pro Lux Mag-Safe Black",
  "6, ZAGIPH16PMILSNPIRI, Zagg iPhone Pro Milan Iridescent",
  "7, ZAGIPH16PSCSNPBLA, Zagg iPhone Pro Santa Cruz",
  "8, ZAGIPH16PLSCSNPBLA, Zagg iPhone Plus Santa Cruz",
  "9, ZAGIPH16PLLUXSNPBLA, Zagg iPhone Plus Lux Mag-Safe Black",
  "10, ZAGIPH16LUXSNPBLA, Zagg iPhone Lux Mag-Safe Black",
  "11, ZAGIPH16MILSNPIRI, Zagg iPhone Milan Iridescent",
  "12, ZAGIPH16SCSNPBLA, Zagg iPhone Santa Cruz MagSafe",
  "13, ZAGIPH15CPCSECLR, Zagg Crystal Palace Graphene Case iPhone 15/14/13",
  "14, ZAGIPH15MANCSEBLA, Zagg Manhatten iPhone Manhatten Case Black",
  "15, ZAGIPH16ELUXBUN, Zagg Bundle iPhone 16E/14/13",
  "16, ZAGIPH16ECPCSECLR, Zagg CP Case iPhone 16E/15/14/13",
  "17, ZAGIPH16ESCCSEBLA, Zagg SC Case iPhone 16E/15/14/13",
  "18, ZAGSAMS25UMILBLU, Zagg S25 U Milan Case - Blue",
  "19, ZAGSAMS25UCPCSECLR, Zagg S25 U CP Case",
  "20, ZAGSAMS25ULUXBUN, Zagg S25 Ultra Luxe Bundle",
  "21, ZAGSAMS25ULUXBLA, Zagg S25 U Luxe Case - Black",
  "22, ZAGSAMS25ULUXBLU, Zagg S25 U Luxe Case - Blue",
  "23, ZAGSAMS25PLUXBUN, Zagg S25+ Luxe Bundle",
  "24, ZAGSAMS25MILBLU, Zagg S25 Milan Case - Blue",
  "25, ZAGSAMS25CPCSECLR, Zagg S25 Crystal Palace Case",
  "26, ZAGSAMS25LUXBUN, Zagg S25 Luxe Bundle",
  "27, ZAGSAMS25LUXBLA, Zagg S25 Luxe Case - Black",
  "28, ZAGSAMS25LUXBLU, Zagg S25 Luxe Case - Blue",
  "29, ZAGSAMS24LUXBUN, Zagg S24 Luxe Bundle",
  "30, ZAGSAMS24FECPCSECLR, Zagg S24 FE Crystal Palace Case - Clear",
  "31, ZAGSAMS24FELUXBUN, Zagg S24 FE Luxe Bundle",
  "32, ZAGSAMS24FELUXBLA, Zagg S24 FE Luxe Case - Black",
  "33, ZAGSAMA56LUXBUN, New Zagg A56 Luxe Bundle",
  "34, ZAGSAMA36LUXCSEBLA, New Zagg A36 Luxe Case - Black",
  "35, ZAGSAMA26LUXBUN, New Zagg A26 Luxe Bundle",
  "36, ZAGSAMA16LUXCSEBLA, Zagg A16 Luxe Case - Black",
  "37, DEFIPH16PMFOLIOBLA, Defence iPhone PM Folio Case Black",
  "38, DEFIPH16PMCSECLR, Defence iPhone Pro Max Case Clear",
  "39, DEFIPH16PFOLIOBLA, Defence iPhone Pro Folio Case Black",
  "40, DEFIPH16PCSECLR, Defence iPhone Pro Case Clear",
  "41, DEFIPH16PLCSECLR, Defence iPhone Plus Case Clear",
  "42, DEFIPH16FOLIOBLA, Defence iPhone Folio Case Black",
  "43, DEFIPH16CSECLR, Defence iPhone Case Clear",
  "44, DEFIPH16EBUND, Defence Bundle iPhone 16E/14/13",
  "45, DEFIPH16ECSECLR, Defence Case iPhone 16E/15/14/13",
  "46, DEFIPH15FOLBLA, Defence Folio iPhone 15/14/13",
  "47, DEFIPH15CSECLR, Defence Clear Case iPhone 15/14/13",
  "48, DEFIPH12CLRCASECLR, Defence Case Apple iPhone 12/12 Pro screen Clear",
  "49, DEFSAMS25UFOLIOBLK, Defence S25 U Folio - Black",
  "50, DEFSAMS25FOLIOBLK, Defence S25 Folio - Black",
  "51, DEFSAMA56FOLIOBLA, New Defence A56 Folio Case",
  "52, DEFSAMA56BUN, New Defence A56 Bundle",
  "53, DEFSAMA56CSECLR, New Defence A56 Clear Case",
  "54, DEFSAMA36FOLIOBLA, New Defence A36 Folio Case",
  "55, DEFSAMA36BUN, New Defence A36 Bundle",
  "56, DEFSAMA36CSECLR, New Defence A36 Clear Case",
  "57, DEFSAMA26FOLIOBLA, New Defence A26 Folio Case",
  "58, DEFSAMA26BUN, New Defence A26 Bundle",
  "59, DEFSAMA26CSECLR, New Defence A26 Clear Case",
  "60, DEFSAMA16OLIOBLA, Defence A16 Folio Case",
  "61, DEFSAMA16CSECLR, Defence A16 Clear Case",
  "62, DEFSAMA16BUN, Defence A16 Bundle",
  "63, DEFSAMA56SP, New Defence A56 Screen Protector",
  "64, DEFSAMA36SP, New Defence A36 Screen Protector",
  "65, DEFSAMA26SP, New Defence A26 Screen Protector",
  "66, DEFSAMA16SP, Defence A16 Screen Protector",
  "67, DEFSAMA16SP, Defence A16 Screen Protector",
  "68, DEFSAMA16SP, Defence A16 Screen Protector",
  "69, DBIPH16PMROSKILBLA, Roskilde MagSafe iPhone Pro Max Black",
  "70, DBIPH16PMICELNDCLR, Iceland D3O MagSafe iPhone Pro Max",
  "71, DBIPH16PROSKILDBLA, Roskilde MagSafe iPhone Pro Black",
  "72, DBIPH16PICELANDCLR, Iceland D3O MagSafe iPhone Pro Clear",
  "73, DBIPH16PLROSKILBLA, Roskilde MagSafe iPhone Plus Black",
  "74, DBIPH16PLICELNDCLR, Iceland D3O MagSafe iPhone Plus Clear",
  "75, DBIPH16ROSKILDBLA, Roskilde MagSafe Case iPhone Black",
  "76, DBIPH16ICELANDCLR, Iceland D3O MagSafe Case iPhone Clear",
  "77, INVIPH13GLSELITE, Invisible Shield Glass Elite for iPhone 12s/ 12s Pro",
  "78, INVSAMS25UXTRSP, InvisibleShield S25 U XTR4 SP",
  "79, INVSAMS25UGLSSP, InvisibleShield S25 U SP",
  "80, INVSAMS25UCAMSP, InvisibleShield S25 Ultra CP",
  "81, INVSAMS25XTRSP, InvisibleShield S25 XTR4 SP",
  "82, INVSAMS25GLSSP, InvisibleShield S25 SP",
  "83, INVSAMS25CAMSP, InvisibleShield S25 CP",
  "84, INVSAMS24FEGLSSP, InvisibleShield S24 FE Glass Elite Screen Protector",
  "85, CGIPH16PMGLSSP, Clearguard iPhone PM Screen Protector",
  "86, CGIPH16PLGLSSP, Clearguard iPhone PL Screen Protector",
  "87, CGIPH16PGLSSP, Clearguard iPhone P Screen Protector",
  "88, CGIPH16GLSSP, Clearguard iPhone Screen Protector",
  "89, CGIPH15PLGLSSP, ClearGuard Glass Screen Protector iPhone Plus",
  "90, CGIPH15GLSSP, ClearGuard Glass Screen Protector iPhone",
  "91, CGIPH13PGLSSCRNPRO, Clear Guard for iPhone 12s/12s Pro"
];


var dataArray2 = [
  "Inside, 3, 6, 5",
  "1, INVPIX9PFLDGLSELTSP, Zagg Pixel Pro Fold GlassScreen Protector",
  "2, ZAGPIX9PXLLUXBUN, Zagg Pixel Pro XL Luxe Bundle",
  "3, ZAGPIX9PXLCPCSECLR, Zagg Pixel Pro XL Crystal Palace Case",
  "4, ZAGPIX9PXLMILCSEIRI, Zagg Pixel Pro XL Milan Case",
  "5, INVPIX9PXLGLSELTSP, Zagg Pixel Pro XL Glass Screen Protector",
  "6, ZAGPIX9PXLLUXCSEBLA, Zagg Pixel Pro XL Luxe Case",
  "7, ZAGPIX9LUXBUN, Zagg Pixel Luxe Bundle",
  "8, ZAGPIX9CPCSECLR, Zagg Pixel Crystal Palace Case",
  "9, ZAGPIX9MILCSEIRI, Zagg Pixel Milan Case",
  "10, ZAGPIX9LUXCSEBLA, Zagg Pixel Luxe Case",
  "11, INVPIX9GLSELTSP, Zagg Pixel Glass Screen Protector",
  "12, ZAGGOOPIX9AMILGLI, New Zagg Pixel 9A Milan Case - Glitter",
  "13, ZAGGOOPIX9ALUXBLA, New Zagg Pixel 9A Luxe Case - Black",
  "14, ZAGGOOPIX9ALUXBUN, New Zagg Pixel 9A Luxe Bundle",
  "15, ZAGGOOPIX8ALUXBUN, Zagg Pixel 8A Luxe Bundle",
  "16, DEFGOOPIX9ABUN, New Defence Pixel 9A Bundle",
  "17, DEFGOOPIX9ASP, New Defence Pixel 9A Screen Protector",
  "18, DEFGOOPIX8ABUNDLE, Defence Pixel 8A Bundle",
  "19, DEFGOOPIX8ACSECLR, Defence Pixel 8A Clear Case",
  "20, DEFGOOPIX8ASP, Defence Pixel 8A Screen Protector",
  "21, DBGOOPIX9ICECSE, Dbramante Iceland Pro Case Pixel",
  "22, DBGOOPIX9PICECSE, Dbramante Iceland Pro Case Pixel Pro XL",
  "23, DBGOOPIX8AGREENCLR, Dbramante Pixel Greenland 8A Clear",
  "24, GOOPIX9PXLCSEBLA, Google Pixel Pro XL Case - Black",
  "25, GOOPIX9PXLCSEWHI, Google Pixel Pro XL Case - White",
  "26, GOOPIX9CSEBLA, Google Pixel 9/Pro Case - Black",
  "27, GOOPIX9CSEPIN, Google Pixel 9/Pro Case - Pink",
  "28, GOOPIX9ACSEBLA, New Pixel 9A Case - Black",
  "29, GOOPIX9ACSEWHI, New Pixel 9A Case - White",
  "30, GOOPIX9ACSEWHI, New Pixel 9A Case - White",
  "31, GOOPIX8ACSEBLA, Google Pixel 8A Obsidian",
  "32, GOOPIX8ACSEWHI, Google Pixel 8A Porcelain",
  "33, INVGOOPIX9AGLSSP, New InvisibleShield Pixel 9A Glass Screen Protector",
  "34, INVGOOPIX8ASP, InvisibleShield Pixel 8A Glass Screen Protector",
  "35, INT256GBMICROSDU3BLA, Integral 256GB Mirco SD Card",
  "36, INT128GBMICROSDU3BLA, Integral 128GB Mirco SD Card",
  "37, INT64GBMICROSDU3BLA, Integral 64GB Mirco SD Card",
  "38, INT32GBMICROSDU1BLA, Integral 32GB Mirco SD Card",
  "39, SBSDASHWLSCGRBLA, SBS In-Car holder with wireless charger",
  "40, SBSDASHHOLDERBLA, SBS In-Car dash or windscreen holder",
  "41, SBSVENTMOUNTBLA, SBS In-Car vent mount black",
  "42, SBSVENTCLIPBLA, SBS In-Car vent clip black",
  "43, SBSVENTCLIPBLA, SBS In-Car vent clip black",
  "44, SLB65WMAINSCHGBLA, SilverLabel 65W Charger",
  "45, SLB45WMAINSCHGBLA, SilverLabel 45W Charger",
  "46, SLB33WMAINSCHGBLA, SilverLabel 25/30w Charger",
  "47, SLB20WMAINSCHGBLA, SilverLabel 20w Charger",
  "48, SLB15WMAGSFECHRGBLA, SilverLabel 15w Mag-Safe Charger",
  "49, SLB15WMAGSFECHRGWHI, SilverLabel 15w Mag-Safe Charger White",
  "50, SLB10KMAGPOWBNKBLA, SilverLabel 10K MagSafe",
  "51, SLB5KMAGPOWBNKBLA, SilverLabel 5K MagSafe",
  "52, SLB15WWLSCHRGBLA, SilverLabel 15w Wireless Charger",
  "53, SLB20WCARCHRGBLA, SilverLabel 20w Car Charger",
  "54, SLB2PORTCARCHRGBLA, SilverLabel Multi Port Car Charger 33W",
  "55, SLB3IN1CHRGSTNDBLA, SilverLabel in Charging stand",
  "56, SLB2IN1CHRGSTNDBLA, SilverLabel in Charging stand",
  "57, SLB18WPD1MA2LBUNBLA, SilverLabel Charger and Lightning Cable Bundle",
  "58, SLB18WPD1MA2CBUNBLA, SilverLabel Charger and USB-C Cable Bundle",
  "59, SLB1MC2C100WCABBLA, SilverLabel 100W 1m Cable braided",
  "60, SLB3MC2LBRDCABBLA, SilverLabel 3m USB-C Lighting Cable White braided",
  "61, SLB2MC2LBRDCABBLA, SilverLabel 2m USB- C Lighting Cable Black braided",
  "62, SLB2MC2LBRDCABWHI, SilverLabel 2m USB-C Lighting Cable White braided",
  "63, SLB3MUSBC2LCABWHI, SilverLabel 3m USB-C Lighting Cable White",
  "64, SLB1MUSBC2LCABBLA, SilverLabel 1m USB- C Lighting Cable Black",
  "65, SLB1MUSBC2LCABWHI, SilverLabel 1m USB-C Lighting Cable White",
  "66, SLB2MA2LBRDCABWHI, SilverLabel 2m USB-A Lighting Cable White braided",
  "67, SLB1MUSBA2LCABWHI, SilverLabel 1m USB-A Lighting Cable White",
  "68, SLB2MC2CBRDCABBLA, SilverLabel 2m USB-C- USB-C Cable Black braided",
  "69, SLB2MC2CBRDCABWHI, SilverLabel 2m USB-C- USB-C Cable White braided",
  "70, SLB3MUSBC2CCABBLA, SilverLabel 3m USB-C- USB-C Cable Black",
  "71, SLB3MUSBC2CCABWHI, SilverLabel 3m USB-C- USB-C Cable White",
  "72, SLB1MUSBC2CCABBLA, SilverLabel 1m USB-C- USB-C Cable Black",
  "73, SLB1MUSBC2CCABWHI, SilverLabel 1m USB-C- USB-C Cable White",
  "74, SLB2MA2CBRDCABBLA, SilverLabel 2m USB-A- USB-C Cable Black braided",
  "75, SLB1MUSBA2CCABBLA, SilverLabel 1m USB-A- USB-C Cable Black",
  "76, SLB1MMICROUSBCABBLA, SilverLabel 1m Micro USB Cable Black",
  "77, SLB20KPOWERBANKBLA, SilverLabel 20,0000mAh Powerbank Black",
  "78, SLB20KPOWERBANKWHI, SilverLabel 20,0000mAh Powerbank White",
  "79, SLB10KPOWERBANKBLA, SilverLabel 10,000mAh Powerbank Black",
  "80, SLB10KPOWERBANKBLA, SilverLabel 10,000mAh Powerbank Black",
  "81, SLB10KPOWERBANKWHI, SilverLabel 10,000mAh Powerbank White",
  "82, SLB10KPOWERBANKWHI, SilverLabel 10,000mAh Powerbank White",
  "83, SLB5KPOWERBANKBLA, SilverLabel 5000mAh Powerbank Black",
  "84, SLB5KPOWERBANKBLA, SilverLabel 5000mAh Powerbank Black",
  "85, SLB5KPOWERBANKWHI, SilverLabel 5000mAh Powerbank White",
  "86, BEL15WCNVRTMAGBLA, Belkin 15w Car Vent Mount",
  "87, APPEARPODSUSBCWHI, New Apple Earpods USB-C White",
  "88, APPMAGSAFEWLCHARGWHI, Apple MagSafe Wireless 15W Charger",
  "89, APP20WUSBCADAPTERWHI, Apple 20W USB-C Power Adapter",
  "90, APP20WUSBCADAPTERWHI, Apple 20W USB-C Power Adapter"
];

var dataArray3 = [
  "Samsung, 2, 4, 4",
  "1, SAM25ULTHCSEBRO, Kindsuit Faux Leather Case for Galaxy S25 Ultra - Camel",
  "2, SAMS25UGRPCSEGRE, Standing Grip Case for Galaxy S25 Ultra - Grey",
  "3, SAMS25USILCSEBLA, Silicone Case for Galaxy S25 Ultra - Black",
  "4, SAMS25UMAGCSECLR, Magnet Clear Case for Galaxy S25 Ultra",
  "5, SAMS25USILCSEBLU, Silicone Case for Galaxy S25 Ultra - Light Blue",
  "6, SAMS25UCSECLR, Clear Case for Galaxy S25 Ultra",
  "7, SAMS25PSILCSEBLA, Silicone Case for Galaxy S25+ - Black",
  "8, SAMS25PMAGCSECLR, Magnet Clear Case for Galaxy S25+",
  "9, SAMS25PCSECLR, Clear Case for Galaxy S25+",
  "10, SAM25LTHCSEBRO, Kindsuit Faux Leather Case S25 - Camel",
  "11, SAMS25GRPCSEGRE, Standing Grip Case for Galaxy S25 - Grey",
  "12, SAMS25SILCSEBLA, Silicone Case for Galaxy S25 - Black",
  "13, SAMS25SILCSEBLU, Silicone Case for Galaxy S25 - Light Blue",
  "14, SAMS25MAGCSECLR, Magnet Clear Case for Galaxy S25",
  "15, SAMS25CSECLR, Clear Case for Galaxy S25",
  "16, SAMS24SUITCSEWHI, Suit Case for Galaxy S24",
  "17, SAMS24SMTVWCSEBLA, Smart View Wallet Case for S24",
  "18, SAMS24FECSECLR, Samsung S24 FE Case - Clear",
  "19, SAMS24FESILCSEGRY, Samsung S24 FE Silicone Case - Grey",
  "20, SAMA56CSECLR, Samsung A56 Clear Case",
  "21, SAMA56RUGCSEBLA, Samsung A56 Rugged Case",
  "22, SAMA36CSECLR, Samsung A36 Clear Case",
  "23, SAMA36RUGCSEBLA, Samsung A36 Rugged Case",
  "24, SAMA26CSECLR, Samsung A26 Clear Case",
  "25, SAMA26RUGCSEBLA, Samsung A26 Rugged Case",
  "26, SAMA16CSECLR, Samsung A16 Case - Clear",
  "27, SAMA05SCSECLR, Samsung A05S Clear Case",
  "28, SAMFLIP6CSECLR, Samsung Flip6 Clear Case",
  "29, SAM45WFASTCGRBLA, Samsung 45W Fast Charger",
  "30, SAM25WFASTCGRBLA, Samsung 25W Charger",
  "31, SAM10K25WPBBLA, Samsung 10K 25W Power bank",
  "32, SAMGALAXYTAG2BLA, Samsung Galaxy Smart Tag2"
];

var dataArray4 = [
  "Zag, 2, 3, 4",
  "1, ZAGIPH16PMMANSNPBLA, Zagg Man Snap iPhone 16 Pro Max Case Black",
  "2, ZAGIPH16PMCPSNPCLR, Zagg CP Snap iPhone 16 PM Case Clear",
  "3, ZAGIPH16PMCPCSECLR, Zagg CP iPhone 16 Pro Max Case Clear",
  "4, INVIPH16PMXTRSP, InvisibleShield Glass XTR4 iPh16PM SP",
  "5, INVIPH16PMPRGLSELISP, InvisibleShield Privacy iPh16PM SP",
  "6, ZAGIPH16PCPSNPCLR, Zagg CP Snap iPhone 16 Pro Case Clear",
  "7, ZAGIPH16PMANSNPBLA, Zagg Man Snap iPhone 16 Pro Case Black",
  "8, ZAGIPH16PCPCSECLR, Zagg CP iPhone 16 Pro Case Clear",
  "9, INVIPH16PXTRSP, InvisibleShield Glass XTR4 iPh16P SP",
  "10, INVIPH16PPRGLSELISP, InvisibleShield Privacy iPh16P SP",
  "11, ZAGIPH16PLMANSNPBLA, Zagg Man Snap iPhone 16 Plus Case Black",
  "12, ZAGIPH16PLCPSNPCLR, Zagg CP Snap iPhone 16 Plus Case Clear",
  "13, ZAGIPH16PLCPCSECLR, Zagg CP iPhone 16 Plus Case Clear",
  "14, INVIPH16PROCAMSP, InvisibleShield iPh16 Pro Camera SP",
  "15, INVIPH16PLPRGLSELISP, InvisibleShield Privacy iPh16PL SP",
  "16, ZAGIPH16MANSNPBLA, Zagg Man Snap iPhone 16 Case Black",
  "17, ZAGIPH16CPSNPCLR, Zagg CP Snap iPhone 16 Case Clear",
  "18, ZAGIPH16CPCSECLR, Zagg CP iPhone 16 Case Clear",
  "19, INVIPH16PRGLSELISP, InvisibleShield Privacy iPh16 SP",
  "20, INVIPH16GLSELISP, InvisibleShield iPh16 Screen Protector",
  "21, INVIPH16PMGLSELISP, InvisibleShield iPh16PM Screen Protector",
  "22, INVIPH16PGLSELISP, InvisibleShield iPh16P Screen Protector",
  "23, INVIPH16PLGLSELISP, InvisibleShield iPh16PL Screen Protector",
  "24, INVIPH16CAMSP, InvisibleShield iPh16 Camera SP"
];
